blank_issues_enabled: false
contact_links:
  - name: For help with other issues, also join our Discord community
    url: https://discord.gg/fPbPhrQNSz
    about: This is a way for getting help with other issues related to Chunks Fade In or just chatting!
