name: Publish release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 720811
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: JaNmzvA8
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          modrinth-featured: false

          github-token: "${{secrets.GITHUB_TOKEN}}"

          loaders: |
            fabric
            quilt

          java: |
            17
            18
            21